# Generated by Django 3.1.5 on 2021-01-18 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterKegiatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian_kegiatan', models.TextField()),
                ('butir_kegiatan', models.CharField(max_length=100)),
                ('subject_matter', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
