# Generated by Django 3.1.5 on 2021-01-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210118_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkegiatan',
            name='subject_matter',
            field=models.CharField(choices=[('0', 'Fungsional Umum'), ('1', 'Statistisi Pelaksana'), ('2', 'Statistisi Pelaksana Lanjutan'), ('3', 'Statistisi Penyelia'), ('4', 'Statistisi Pertama'), ('5', 'Statistisi Muda'), ('6', 'Statistisi Madya'), ('7', 'Statistisi Utama'), ('8', 'Pranata Komputer Terampil'), ('9', 'Pranata Komputer Mahir'), ('10', 'Pranata Komputer Penyelia'), ('11', 'Pranata Komputer Ahli Pertama'), ('12', 'Pranata Komputer Ahli Muda'), ('13', 'Pranata Komputer Ahli Madya'), ('14', 'Pranata Komputer Ahli Utama')], default='7', max_length=80),
        ),
    ]
