# Generated by Django 3.1.5 on 2021-01-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210120_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkegiatan',
            name='subject_matter',
            field=models.CharField(choices=[('1', 'Kepala BPS'), ('2', 'Kepala Subbagian Umum'), ('3', 'Koordinator Fungsi Statistik Sosial'), ('4', 'Koordinator Fungsi Statistik Produksi'), ('5', 'Koordinator Fungsi Statistik Distribusi'), ('6', 'Koordinator Fungsi Neraca Wilayah dan Analisis Statistik'), ('7', 'Koordinator Fungsi Integrasi Pengolahan dan Diseminasi Statistik'), ('8', 'Staf'), ('9', 'KSK')], default='7', max_length=80),
        ),
    ]
