# Generated by Django 3.1.5 on 2021-01-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_masterkegiatan_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkegiatan',
            name='satuan',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
