# Generated by Django 3.1.5 on 2021-01-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210128_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkegiatan',
            name='butir_kegiatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.masterbutirkegiatan'),
        ),
    ]
