# Generated by Django 3.1.5 on 2021-03-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210128_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkegiatan',
            name='satuan',
            field=models.CharField(max_length=30),
        ),
    ]
