# Generated by Django 3.1.5 on 2021-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210317_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butirckp',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
    ]
