# Generated by Django 3.1.5 on 2021-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210317_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butirckp',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='butirckp',
            name='realisasi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='butirckp',
            name='tingkat_kualitas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
