# Generated by Django 3.1.5 on 2021-03-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210317_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbutirkegiatan',
            name='jenis_fungsional',
            field=models.CharField(blank=True, choices=[('ST', 'Statistisi'), ('PR', 'Pranata Komputer'), (None, '----- Bukan Kegiatan Fungsional -----')], max_length=30),
        ),
        migrations.AlterField(
            model_name='masterbutirkegiatan',
            name='pelaksana_kegiatan',
            field=models.CharField(blank=True, choices=[('1', 'Pertama'), ('2', 'Muda'), ('3', 'Madya'), ('4', 'Utama'), ('5', 'Semua Jenjang'), (None, '----- Bukan Kegiatan Fungsional -----')], max_length=30),
        ),
    ]
