# Generated by Django 3.1.5 on 2021-07-28 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210723_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkegiatan',
            name='butir_kegiatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.masterbutirkegiatan'),
        ),
    ]
