# Generated by Django 3.1.5 on 2021-09-28 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0018_auto_20210728_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateTimeField(null=True)),
                ('profesional', models.FloatField(null=True)),
                ('integritas', models.FloatField(null=True)),
                ('amanah', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('pegawai_dinilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai_dinilai', to=settings.AUTH_USER_MODEL)),
                ('pegawai_penilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai_penilai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
