# Generated by Django 3.1.5 on 2021-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210930_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pia',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
