# Generated by Django 3.1.5 on 2021-10-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20211001_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butirckp',
            name='realisasi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='butirckp',
            name='target',
            field=models.FloatField(),
        ),
    ]
