# Generated by Django 3.1.5 on 2021-07-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210707_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_profil',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
